<?php

use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\PasswordController;
use App\Http\Controllers\Auth\TwoFactorController;
use App\Http\Controllers\BranchController;
use App\Http\Controllers\CabinetController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DocumentationController;
use App\Http\Controllers\DropRouteMaintenanceController;
use App\Http\Controllers\FiberManagementController;
use App\Http\Controllers\FiberSchemaExportController;
use App\Http\Controllers\GisController;
use App\Http\Controllers\HealthController;
use App\Http\Controllers\HouseController;
use App\Http\Controllers\MapController;
use App\Http\Controllers\MapLayerController;
use App\Http\Controllers\MissingDropRouteController;
use App\Http\Controllers\OdfController;
use App\Http\Controllers\ProjectBackupController;
use App\Http\Controllers\ProjectExportController;
use App\Http\Controllers\ProjectGeoJsonController;
use App\Http\Controllers\ProjectManagementController;
use App\Http\Controllers\ProjectMaterialController;
use App\Http\Controllers\ProjectPlanningController;
use App\Http\Controllers\ProjectPrintController;
use App\Http\Controllers\ProjectSettingsController;
use App\Http\Controllers\ProjectSnapshotController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\RouteController;
use App\Http\Controllers\SurveyPointController;
use Illuminate\Support\Facades\Route;

Route::middleware('guest')->group(function (): void {
    Route::get('/prijava', [LoginController::class, 'create'])->name('login');
    Route::post('/prijava', [LoginController::class, 'store'])->name('login.store');
    Route::get('/prijava/2fa', [TwoFactorController::class, 'challenge'])->name('two-factor.challenge');
    Route::post('/prijava/2fa', [TwoFactorController::class, 'verifyChallenge'])->middleware('throttle:6,1')->name('two-factor.verify');
});

Route::middleware('auth')->group(function (): void {
    Route::get('/sistem/health', HealthController::class)->middleware('can:system.manage')->name('system.health');
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
    Route::get('/uputstvo/{document?}', DocumentationController::class)->name('documentation');
    Route::get('/mapa', [MapController::class, 'map'])->name('map.dashboard');
    Route::get('/api/projekti/{project}/map-data', [MapController::class, 'data'])->middleware('can:project.view')->name('api.projects.map-data');
    Route::redirect('/mapa/editor', '/mapa')->name('map.index');
    Route::post('/mapa/plan', [MapController::class, 'storePlan'])->middleware('can:project.edit')->name('map.plan.store');
    Route::post('/mapa/draft', [MapController::class, 'storeDraft'])->middleware('can:project.edit')->name('map.draft.store');
    Route::get('/mapa/auto-route', [MapController::class, 'autoRoute'])->middleware(['can:project.edit', 'throttle:heavy'])->name('map.auto-route');
    Route::post('/mapa/sugestije', [CabinetController::class, 'storeSuggestedCabinets'])->middleware('can:project.edit')->name('map.suggestions.store');
    Route::get('/izvjestaji', [ReportController::class, 'reports'])->name('reports.index');
    Route::post('/izvjestaji/projekti/{project}/stavke-priloga', [ReportController::class, 'storeAppendixItem'])->middleware('can:project.edit')->name('reports.appendix-items.store');
    Route::delete('/izvjestaji/stavke-priloga/{item}', [ReportController::class, 'deleteAppendixItem'])->middleware('can:destructive')->name('reports.appendix-items.delete');
    Route::get('/izvjestaji/projekti/{project}/prilog-3', [ReportController::class, 'projectAppendix'])->name('reports.project-appendix');
    Route::get('/splitteri', [ReportController::class, 'splitters'])->name('splitters.index');
    Route::get('/fiber-sema', [ReportController::class, 'fiberSchema'])->name('fiber-schema.index');
    Route::get('/projekti/{project}/fiber-sema/pdf', [ReportController::class, 'fiberSchemaPdf'])->middleware('can:project.export')->name('projects.fiber-schema-pdf');
    Route::get('/projekti/{project}/fiber-plan', [FiberManagementController::class, 'plan'])->name('projects.fiber.plan');
    Route::get('/projekti/{project}/fiber-plan/csv', [FiberManagementController::class, 'csv'])->middleware('can:project.export')->name('projects.fiber.csv');
    Route::post('/projekti/{project}/fiber-splice', [FiberManagementController::class, 'storeSplice'])->middleware('can:project.edit')->name('projects.fiber.splice.store');
    Route::delete('/projekti/{project}/fiber-splice/{splice}', [FiberManagementController::class, 'destroySplice'])->middleware('can:destructive')->name('projects.fiber.splice.destroy');
    Route::get('/projekti/{project}/fiber-verzije', [FiberManagementController::class, 'versions'])->name('projects.fiber.versions');
    Route::post('/projekti/{project}/fiber-verzije', [FiberManagementController::class, 'storeVersion'])->middleware('can:project.edit')->name('projects.fiber.versions.store');
    Route::get('/projekti/{project}/fiber-verzije/{version}/poredi', [FiberManagementController::class, 'compare'])->name('projects.fiber.versions.compare');
    Route::post('/projekti/{project}/fiber-verzije/{version}/vrati', [FiberManagementController::class, 'restore'])->middleware('can:destructive')->name('projects.fiber.versions.restore');
    Route::patch('/projekti/{project}/fiber-zakljucavanje', [FiberManagementController::class, 'toggleLock'])->middleware('can:project.edit')->name('projects.fiber.lock');
    Route::patch('/projekti/{project}/power-budget', [FiberManagementController::class, 'updateBudgetSettings'])->middleware('can:project.edit')->name('projects.fiber.budget-settings');
    Route::put('/projekti/{project}/fiber-raspored', [FiberManagementController::class, 'storeLayout'])->middleware('can:project.edit')->name('projects.fiber.layout');
    Route::get('/projekti/{project}/fiber-teren/{cabinet}', [FiberManagementController::class, 'fieldSheet'])->middleware('can:project.export')->name('projects.fiber.field-sheet');
    Route::get('/krakovi', [BranchController::class, 'branches'])->name('branches.index');
    Route::post('/krakovi', [BranchController::class, 'storeBranch'])->middleware('can:project.edit')->name('branches.store');
    Route::patch('/krakovi/reorder', [BranchController::class, 'reorderBranches'])->middleware('can:project.edit')->name('branches.reorder');
    Route::match(['put', 'patch'], '/krakovi/{id}', [BranchController::class, 'updateBranch'])->middleware('can:project.edit')->name('branches.update');
    Route::delete('/krakovi/{id}', [BranchController::class, 'deleteBranch'])->middleware('can:destructive')->name('branches.delete');
    Route::get('/provjera-projekta', [ProjectSettingsController::class, 'projectCheck'])->name('project-check.index');
    Route::get('/postavke', [ProjectSettingsController::class, 'settings'])->middleware('can:settings.manage')->name('settings.index');
    Route::get('/postavke/backup', [ProjectSettingsController::class, 'backup'])->middleware('can:settings.manage')->name('settings.backup');
    Route::post('/postavke/gis/import', [GisController::class, 'import'])->middleware(['can:settings.manage', 'throttle:heavy'])->name('gis.import');
    Route::get('/postavke/gis/{project}/slojevi', [GisController::class, 'layers'])->middleware('can:settings.manage')->name('gis.layers');
    Route::delete('/postavke/gis/{project}/slojevi/{type}', [GisController::class, 'destroyLayer'])->middleware('can:destructive')->name('gis.layers.destroy');

    Route::get('/projekti', [ProjectManagementController::class, 'index'])->name('projects.index');
    Route::post('/projekti', [ProjectManagementController::class, 'store'])->middleware('can:project.edit')->name('projects.store');
    Route::get('/projekti/{project}/pregled', [ProjectManagementController::class, 'show'])->name('projects.show');
    Route::match(['put', 'patch'], '/projekti/{id}', [ProjectManagementController::class, 'update'])->middleware('can:project.edit')->name('projects.update');
    Route::post('/projekti/{project}/odo-plan/preview', [ProjectPlanningController::class, 'previewOdo'])->middleware(['can:project.edit', 'throttle:heavy'])->name('projects.odo-plan.preview');
    Route::get('/projekti/{project}/gis-plan/preview', [ProjectPlanningController::class, 'previewGis'])->middleware(['can:project.edit', 'throttle:heavy'])->name('projects.gis-plan.preview');
    Route::post('/projekti/{project}/gis-plan/confirm', [ProjectPlanningController::class, 'confirmGis'])->middleware('can:project.edit')->name('projects.gis-plan.confirm');
    Route::post('/projekti/{project}/odo-plan/confirm', [ProjectPlanningController::class, 'confirmOdo'])->middleware('can:project.edit')->name('projects.odo-plan.confirm');
    Route::get('/projekti/{project}/validacija', [ProjectPlanningController::class, 'validateProject'])->name('projects.validation');
    Route::get('/projekti/{project}/snapshoti', [ProjectSnapshotController::class, 'index'])->name('projects.snapshots.index');
    Route::post('/projekti/{project}/snapshoti', [ProjectSnapshotController::class, 'store'])->middleware('can:project.backup')->name('projects.snapshots.store');
    Route::post('/projekti/{project}/snapshoti/{snapshot}/vrati', [ProjectSnapshotController::class, 'restore'])->middleware('can:destructive')->name('projects.snapshots.restore');
    Route::get('/projekti/{project}/snapshoti/{snapshot}/download', [ProjectSnapshotController::class, 'download'])->middleware('can:project.backup')->name('projects.snapshots.download');
    Route::post('/projekti/{project}/materijali/izracunaj', ProjectMaterialController::class)->middleware('can:project.edit')->name('materials.calculate');
    Route::post('/projekti/{project}/drop-trase/popuni', MissingDropRouteController::class)->middleware('can:project.edit')->name('projects.drop-routes.fill');
    Route::get('/projekti/{project}/drop-trase/audit', [DropRouteMaintenanceController::class, 'audit'])->name('projects.drop-routes.audit');
    Route::post('/projekti/{project}/drop-trase/popravi', [DropRouteMaintenanceController::class, 'repair'])->middleware('can:project.edit')->name('projects.drop-routes.repair');
    Route::post('/projekti/{project}/tacke/preview', [SurveyPointController::class, 'preview'])->middleware(['can:project.edit', 'throttle:heavy'])->name('projects.survey-points.preview');
    Route::post('/projekti/{project}/tacke/preview-izvjestaj/{format}', [SurveyPointController::class, 'previewReport'])->middleware(['can:project.edit', 'throttle:heavy'])->where('format', 'csv|pdf')->name('projects.survey-points.preview-report');
    Route::post('/projekti/{project}/tacke/import', [SurveyPointController::class, 'import'])->middleware(['can:project.edit', 'throttle:heavy'])->name('projects.survey-points.import');
    Route::get('/projekti/{project}/tacke/importi', [SurveyPointController::class, 'imports'])->name('projects.survey-points.imports');
    Route::delete('/projekti/{project}/tacke/importi/{batch}', [SurveyPointController::class, 'destroyImport'])->middleware('can:destructive')->where('batch', '[a-f0-9]{40}')->name('projects.survey-points.imports.destroy');
    Route::post('/projekti/{project}/teren/tacke', [SurveyPointController::class, 'storeFieldPoint'])->middleware('can:field.capture')->name('projects.field-points.store');
    Route::get('/projekti/{project}/teren/tacke/{point}/fotografija', [SurveyPointController::class, 'fieldPointPhoto'])->name('projects.field-points.photo');
    Route::delete('/projekti/{project}/tacke', [SurveyPointController::class, 'destroy'])->middleware('can:destructive')->name('projects.survey-points.destroy');
    Route::get('/projekti/{project}/geojson', ProjectGeoJsonController::class)->middleware('can:project.export')->name('projects.geojson');
    Route::post('/projekti/{project}/dxf', [ProjectExportController::class, 'exportDxf'])->middleware(['can:project.export', 'throttle:heavy'])->name('projects.dxf');
    Route::get('/projekti/{project}/fiber-schema-dxf', [FiberSchemaExportController::class, 'exportFiberSchema'])->middleware(['can:project.export', 'throttle:heavy'])->name('projects.fiber-schema-dxf');
    Route::get('/projekti/{project}/backup', [ProjectBackupController::class, 'backup'])->middleware('can:project.backup')->name('projects.backup');
    Route::post('/projekti/restore', [ProjectBackupController::class, 'restore'])->middleware(['can:destructive', 'throttle:heavy'])->name('projects.restore');
    Route::get('/projekti/{project}/print', ProjectPrintController::class)->middleware('can:project.export')->name('projects.print');
    Route::delete('/projekti/{id}', [ProjectManagementController::class, 'destroy'])->middleware('can:destructive')->name('projects.delete');

    Route::get('/odf', [OdfController::class, 'odfs'])->name('odfs.index');
    Route::post('/odf', [OdfController::class, 'storeOdf'])->middleware('can:project.edit')->name('odfs.store');
    Route::match(['put', 'patch'], '/odf/{id}', [OdfController::class, 'updateOdf'])->middleware('can:project.edit')->name('odfs.update');
    Route::patch('/odf/{id}/pozicija', [OdfController::class, 'updateOdfPosition'])->middleware('can:project.edit')->name('odfs.position.update');
    Route::delete('/odf/{id}', [OdfController::class, 'deleteOdf'])->middleware('can:destructive')->name('odfs.delete');

    Route::get('/ormarici', [CabinetController::class, 'cabinets'])->name('cabinets.index');
    Route::post('/ormarici', [CabinetController::class, 'storeCabinet'])->middleware('can:project.edit')->name('cabinets.store');
    Route::match(['put', 'patch'], '/ormarici/{id}', [CabinetController::class, 'updateCabinet'])->middleware('can:project.edit')->name('cabinets.update');
    Route::patch('/ormarici/{id}/pozicija', [CabinetController::class, 'updateCabinetPosition'])->middleware('can:project.edit')->name('cabinets.position.update');
    Route::delete('/ormarici/{id}', [CabinetController::class, 'deleteCabinet'])->middleware('can:destructive')->name('cabinets.delete');

    Route::get('/kuce', [HouseController::class, 'houses'])->name('houses.index');
    Route::post('/kuce', [HouseController::class, 'storeHouse'])->middleware('can:project.edit')->name('houses.store');
    Route::match(['put', 'patch'], '/kuce/{id}', [HouseController::class, 'updateHouse'])->middleware('can:project.edit')->name('houses.update');
    Route::patch('/kuce/{id}/pozicija', [HouseController::class, 'updateHousePosition'])->middleware('can:project.edit')->name('houses.position.update');
    Route::post('/ormarici/{id}/povezi-kuce', [HouseController::class, 'connectCabinetHouses'])->middleware('can:project.edit')->name('cabinets.houses.connect');
    Route::delete('/kuce/{id}', [HouseController::class, 'deleteHouse'])->middleware('can:destructive')->name('houses.delete');

    Route::get('/trase', [RouteController::class, 'routes'])->name('routes.index');
    Route::post('/trase', [RouteController::class, 'storeRoute'])->middleware('can:project.edit')->name('routes.store');
    Route::match(['put', 'patch'], '/trase/{id}', [RouteController::class, 'updateRoute'])->middleware('can:project.edit')->name('routes.update');
    Route::patch('/trase/{id}/geometrija', [RouteController::class, 'updateRouteGeometry'])->middleware('can:project.edit')->name('routes.geometry.update');
    Route::post('/trase/{id}/split', [RouteController::class, 'splitRoute'])->middleware('can:project.edit')->name('routes.split');
    Route::post('/trase/{id}/join', [RouteController::class, 'joinRoutes'])->middleware('can:project.edit')->name('routes.join.multiple');
    Route::post('/trase/{id}/join/{otherId}', [RouteController::class, 'joinRoutes'])->middleware('can:project.edit')->name('routes.join');
    Route::post('/trase/dxf', [RouteController::class, 'importDxf'])->middleware(['can:project.edit', 'throttle:heavy'])->name('routes.dxf.import');
    Route::delete('/trase/{id}', [RouteController::class, 'deleteRoute'])->middleware('can:destructive')->name('routes.delete');

    Route::post('/mapa/dxf-layer', [MapLayerController::class, 'upload'])->middleware(['can:project.edit', 'throttle:heavy'])->name('map.dxf-layer.upload');

    Route::get('/api/notifications', [DashboardController::class, 'notifications'])->name('api.notifications');
    Route::post('/odjava', [LoginController::class, 'destroy'])->name('logout');
    Route::put('/postavke/lozinka', [PasswordController::class, 'update'])->name('password.update');
    Route::get('/postavke/2fa', [TwoFactorController::class, 'setup'])->middleware('can:settings.manage')->name('two-factor.setup');
    Route::post('/postavke/2fa', [TwoFactorController::class, 'confirm'])->middleware('can:settings.manage')->name('two-factor.confirm');
    Route::delete('/postavke/2fa', [TwoFactorController::class, 'destroy'])->middleware('can:settings.manage')->name('two-factor.destroy');
});
